# https://docs.travis-ci.com/user/languages/android/#Overview
# https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-armeabi-v7a-android-17
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

# Bug fix from https://github.com/travis-ci/travis-ci/issues/8879#issuecomment-350534842
before_install:
  - yes | sdkmanager "platforms;android-27"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - echo -e "\nkeystorePath=../debug.keystore" > credentials.properties
  - echo -e "\nkeystorePassword=android" >> credentials.properties
  - echo -e "\nkeystoreItemAlias=androiddebugkey" >> credentials.properties
  - echo -e "\nkeystoreItemPassword=android" >> credentials.properties
  - chmod +x gradlew
  - ./gradlew dependencies || true

script:
  - ./gradlew build connectedCheck -x lint